comptes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("utilisateurs.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # type: ignore

utilisateurs/urls.py
from django.urls import path
from utilisateurs import views

app_name = "utilisateurs"

urlpatterns = [
    path("", views.index_view, name="index"),
    path("profil/<int:pk>/", views.profil_view, name="profil"),
    path("inscription/", views.inscription_view, name="inscription"),
    path("connexion/", views.connexion_view, name="connexion"),
    path("deconnexion/", views.deconnexion_view, name="deconnexion")
]

utilisateurs/models.py
from django.db import models
from django.contrib.auth.models import User

class ProfilUtilisateur(models.Model):
    utilisateur = models.OneToOneField(User, on_delete=models.CASCADE)
    site_portfolio = models.URLField(blank=True)
    photo_de_profil = models.ImageField(upload_to="photos_de_profil", blank=True)

    def __str__(self):
        return self.utilisateur.username

utilisateurs/forms.py
from django import forms
from django.contrib.auth.models import User
from utilisateurs.models import ProfilUtilisateur

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(), label="Mot de passe")
    class Meta:
        model = User
        fields = ["username", "email", "password"]

class ProfilUtilisateurForm(forms.ModelForm):
    class Meta:
        model = ProfilUtilisateur
        fields = ["site_portfolio", "photo_de_profil"]

utilisateurs/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from utilisateurs.models import ProfilUtilisateur
from utilisateurs.forms import UserForm, ProfilUtilisateurForm

def index_view(request):
    return render(request, "utilisateurs/index.html")

@login_required
def profil_view(request, pk) :
    if request.user.pk != pk :
        return redirect("utilisateurs:profil", request.user.pk)
    profil = ProfilUtilisateur.objects.get(utilisateur__pk=pk)
    context = {"profil": profil}
    return render(request, "utilisateurs/profil.html", context)

def inscription_view(request):
    user_form = UserForm()
    profil_utilisateur_form = ProfilUtilisateurForm()
    inscrit = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profil_utilisateur_form = ProfilUtilisateurForm(data=request.POST)
        if user_form.is_valid() and profil_utilisateur_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profil_utilisateur = profil_utilisateur_form.save(commit=False)
            profil_utilisateur.utilisateur = user
            if "photo_de_profil" in request.FILES:
                profil_utilisateur.photo_de_profil = request.FILES["photo_de_profil"]
            profil_utilisateur.save()
            inscrit = True
        else:
            print(user_form.errors, profil_utilisateur_form.errors)
    context = {"user_form": user_form, "profil_utilisateur_form": profil_utilisateur_form, "inscrit": inscrit}
    return render(request, "utilisateurs/inscription.html", context)

def connexion_view(request):
    if request.method == "POST":
        nom_utilisateur = request.POST.get("nom_utilisateur")
        mot_de_passe = request.POST.get("mot_de_passe")
        utilisateur = authenticate(username=nom_utilisateur, password=mot_de_passe)
        if utilisateur:
            if utilisateur.is_active:
                login(request, utilisateur)
                return redirect("utilisateurs:index")
            else:
                return HttpResponse("Compte innactif")
        else:
            return HttpResponse("Identifiants invalides")
    else:
        return render(request, "utilisateurs/connexion.html")

@login_required
def deconnexion_view(request):
    logout(request)
    return redirect("utilisateurs:index")

utilisateurs/templates/utilisateurs/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block titre %}{% endblock titre %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

    {% if user.is_authenticated %}
    <p>(Connecté : {{ user.username }})</p>
    <a href="{% url 'utilisateurs:index' %}">Acceuil</a>
    <a href="{% url 'utilisateurs:profil' user.pk %}">Profil</a>
    <a href="{% url 'utilisateurs:deconnexion' %}">Deconnexion</a>
    {% else %}
    <a href="{% url 'utilisateurs:index' %}">Acceuil</a>
    <a href="{% url 'utilisateurs:connexion' %}">Connexion</a>
    <a href="{% url 'utilisateurs:inscription' %}">Inscription</a>
    {% endif %}    

    {% block contenu %}{% endblock contenu %}
    
</body>
</html>

utilisateurs/templates/utilisateurs/connexion.html
<!DOCTYPE html>
{% extends 'utilisateurs/base.html' %}

{% block titre %}Connexion{% endblock titre %}

{% block contenu %}

<h1>Connectez vous</h1>
<form method="POST">
      {% csrf_token %}
      <label for="nom_utilisateur">Nom d'utilisateur : </label>
      <input type="text" name="nom_utilisateur" placeholder="Nom d'utilisateur">
      <label for="mot_de_passe">Mot de passe : </label>
      <input type="password" name="mot_de_passe">
      <input type="submit" value="Connexion">
</form>

{% endblock contenu %}

utilisateurs/templates/utilisateurs/index.html
<!DOCTYPE html>
{% extends 'utilisateurs/base.html' %}

{% block titre %}Acceuil{% endblock titre %}

{% block contenu %}

<h1>Page d'acceuil</h1>

{% endblock contenu %}

utilisateurs/templates/utilisateurs/inscription.html
<!DOCTYPE html>
{% extends 'utilisateurs/base.html' %}

{% block titre %}Inscription{% endblock titre %}

{% block contenu %}

{% if inscrit %}
<h1>Merci pour votre inscription</h1>
{% else %}
<h1>Inscrivez vous !</h1>
<h3>Formulaire d'inscription :</h3>
<form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profil_utilisateur_form.as_p }}
      <button type="submit">Créer</button>
</form>
{% endif %}

{% endblock contenu %}

utilisateurs/templates/utilisateurs/profil.html
<!DOCTYPE html>
{% extends 'utilisateurs/base.html' %}

{% block titre %}Hello{% endblock titre %}

{% block contenu %}

<p>Nom d’utilisateur : {{ user.username }}</p>
<p>Email : {{ user.email }}</p>
<p>Site portfolio : <a href="{{ profil.site_portfolio }}" target="_blank">{{ profil.site_portfolio }}</a></p>  
<img src="{{ profil.photo_de_profil.url }}" width="200">      

{% endblock contenu %}